In [6]:
%run data.ipynb
# %run negation.ipynb
atomic_neg = pd.read_csv('atomic_neg.csv')
atomic_neg.shape

   Expression          Individual       Example Type
0         Cat       animals#cat01  positive examples
1         Cat       animals#boy01  negative examples
2         Cat    animals#lizard01  negative examples
3         Cat     animals#snake01  negative examples
4         Cat     animals#trout01  negative examples
5         Cat       animals#bat01  negative examples
6         Cat     animals#eagle01  negative examples
7         Cat      animals#trex01  negative examples
8         Cat   animals#ostrich01  negative examples
9         Cat       animals#eel01  negative examples
10        Cat       animals#dog01  negative examples
11        Cat    animals#dragon01  negative examples
12        Cat      animals#girl01  negative examples
13        Cat    animals#turtle01  negative examples
14        Cat     animals#shark01  negative examples
15        Cat   animals#dolphin01  negative examples
16        Cat   animals#herring01  negative examples
17        Cat     animals#croco01  negative examples
18        Cat  animals#platypus01  negative examples
19        Cat   animals#penguin01  negative examples
['positive examples' 'negative examples']
(205976, 3)

(48, 41)

In [7]:
# conj_classes_all = df[df['Expression'].str.contains('⊓')] #& ~df['Expression'].str.contains('[⊔]')] #['¬', '⊔', '⊓']
# conj_classes_all

conj_classes = df[df['Expression'].str.contains('⊓') & ~df['Expression'].str.contains('[⊔]')] #['¬', '⊔', '⊓']
conj_classes

,Expression,Individual,Example Type,Example Encoding
72450,HasEggs ⊓ Homeothermic,animals#eagle01,positive examples,1
72451,HasEggs ⊓ Homeothermic,animals#ostrich01,positive examples,1
72452,HasEggs ⊓ Homeothermic,animals#penguin01,positive examples,1
72453,HasEggs ⊓ Homeothermic,animals#platypus01,positive examples,1
72454,HasEggs ⊓ Homeothermic,animals#eagle01,positive examples,1
...,...,...,...,...
104975,HasEggs ⊓ (¬Shark),animals#shark01,negative examples,0
104976,HasEggs ⊓ (¬Shark),animals#boy01,negative examples,0
104977,HasEggs ⊓ (¬Shark),animals#bat01,negative examples,0
104978,HasEggs ⊓ (¬Shark),animals#dragon01,negative examples,0
104979,HasEggs ⊓ (¬Shark),animals#cat01,negative examples,0

In [8]:
# len(conj_classes['Expression'].unique())
# conj_classes['Expression'].unique()

In [9]:
conj_classes['Expression'] = conj_classes['Expression'].str.replace('(', '')
conj_classes['Expression'] = conj_classes['Expression'].str.replace(')', '')

# Function to split the expression and clean up the parts
def split_and_clean(expression):
    # Split by '⊓'
    parts = expression.split('⊓')
    # Strip whitespace and remove parentheses
    first_part = parts[0].strip()
#     second_part = parts[1].strip().replace('(', '').replace(')', '').replace('¬', '')
    second_part = re.sub(r'[()¬]', '', parts[1].strip())
    return first_part, second_part

# Apply the function to the dataframe and create new columns
# conj_classes[['Part1', 'Part2']] = conj_classes['Expression'].apply(lambda x: x.split('⊓'))
conj_classes[['Part1', 'Part2']] = conj_classes['Expression'].str.split('⊓', n=1, expand=True)
# df
conj_classes['Part1'] = conj_classes['Part1'].str.strip()
conj_classes['Part2'] = conj_classes['Part2'].str.strip()

conj = conj_classes
conj.shape

/tmp/ipykernel_7553/3040752926.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conj_classes['Expression'] = conj_classes['Expression'].str.replace('(', '')
/tmp/ipykernel_7553/3040752926.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conj_classes['Expression'] = conj_classes['Expression'].str.replace(')', '')
/tmp/ipykernel_7553/3040752926.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conj_classes[['Part1', 'Part2']] = conj_classes['Expression'].str.split('⊓', n=1, expand=True)
/tmp/ipykernel_7553/3040752926.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conj_classes[['Part1', 'Part2']] = conj_classes['Expression'].str.split('⊓', n=1, expand=True)
/tmp/ipykernel_7553/3040752926.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conj_classes['Part1'] = conj_classes['Part1'].str.strip()
/tmp/ipykernel_7553/3040752926.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  conj_classes['Part2'] = conj_classes['Part2'].str.strip()

(7330, 6)

In [10]:
# conj['Part1'].unique()
conj['Part2'].unique()

array(['Homeothermic', '¬HasMilk', '¬Cat', '¬Eel', '¬Snake', '¬Dog',
       '¬Turtle', '¬Lizard', '¬Crocodile', '¬Trout', '¬HasEggs', '¬Bat',
       '¬Dolphin', '¬Homeothermic', '¬Herring', '¬Ostrich', '¬Eagle',
       '¬T-Rex', '¬Shark', '¬HasGills'], dtype=object)

In [17]:
conj_ent = pd.merge(conj, ent, left_on='Individual', right_on='Unnamed: 0', how='inner')
conj_ent.columns
conj_ent

,Expression,Individual,Example Type,Example Encoding,Part1,Part2,Unnamed: 0,0,1,2,...,30,31,32,33,34,35,36,37,38,39
0,HasEggs ⊓ Homeothermic,animals#eagle01,positive examples,1,HasEggs,Homeothermic,animals#eagle01,0.303576,-0.257578,0.161850,...,-0.161282,-0.254736,0.055635,-0.190755,-0.121789,-0.243177,-0.154616,-0.201404,-0.135880,0.358249
1,HasEggs ⊓ Homeothermic,animals#ostrich01,positive examples,1,HasEggs,Homeothermic,animals#ostrich01,0.244503,-0.165339,0.238183,...,-0.409302,-0.209357,-0.162140,-0.174516,-0.180736,-0.159218,-0.202043,-0.176716,-0.187154,0.333251
2,HasEggs ⊓ Homeothermic,animals#penguin01,positive examples,1,HasEggs,Homeothermic,animals#penguin01,0.251046,-0.165633,0.311441,...,-0.226317,-0.226226,-0.397666,-0.253572,-0.076575,-0.249241,-0.195753,-0.203878,-0.223741,0.285713
3,HasEggs ⊓ Homeothermic,animals#platypus01,positive examples,1,HasEggs,Homeothermic,animals#platypus01,0.256755,0.015516,0.219961,...,-0.192817,-0.306515,-0.052506,-0.140758,-0.124978,-0.387769,-0.210615,-0.212747,-0.198139,0.202995
4,HasEggs ⊓ Homeothermic,animals#eagle01,positive examples,1,HasEggs,Homeothermic,animals#eagle01,0.303576,-0.257578,0.161850,...,-0.161282,-0.254736,0.055635,-0.190755,-0.121789,-0.243177,-0.154616,-0.201404,-0.135880,0.358249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7325,HasEggs ⊓ ¬Shark,animals#shark01,negative examples,0,HasEggs,¬Shark,animals#shark01,0.265107,0.035628,0.237405,...,-0.227809,-0.170068,-0.419936,-0.280010,-0.032112,-0.230731,-0.102835,-0.188250,-0.221799,0.176027
7326,HasEggs ⊓ ¬Shark,animals#boy01,negative examples,0,HasEggs,¬Shark,animals#boy01,0.326895,-0.017734,0.072276,...,-0.225900,-0.367958,-0.092999,-0.190105,-0.178869,-0.120484,-0.255176,-0.192784,-0.126583,0.257940
7327,HasEggs ⊓ ¬Shark,animals#bat01,negative examples,0,HasEggs,¬Shark,animals#bat01,0.252662,-0.221016,0.193865,...,-0.091240,-0.272894,-0.433999,-0.219100,-0.102484,-0.090931,-0.164620,-0.184859,-0.192803,0.282611
7328,HasEggs ⊓ ¬Shark,animals#dragon01,negative examples,0,HasEggs,¬Shark,animals#dragon01,0.071034,-0.154344,0.204145,...,-0.105758,-0.206320,-0.329204,-0.297947,-0.031028,-0.106839,-0.162115,-0.157035,-0.177537,0.440381
7329,HasEggs ⊓ ¬Shark,animals#cat01,negative examples,0,HasEggs,¬Shark,animals#cat01,0.183570,0.064570,0.119314,...,-0.281544,-0.161038,-0.210074,-0.176184,-0.071090,-0.102411,-0.208158,-0.117546,-0.199348,0.236494

In [18]:
conj_ent = pd.merge(conj_ent, ent, left_on="Part1", right_on='Unnamed: 0', how='inner', suffixes=['_ind', '_cla1'])
conj_ent

,Expression,Individual,Example Type,Example Encoding,Part1,Part2,Unnamed: 0_ind,0_ind,1_ind,2_ind,...,30_cla1,31_cla1,32_cla1,33_cla1,34_cla1,35_cla1,36_cla1,37_cla1,38_cla1,39_cla1
0,HasEggs ⊓ Homeothermic,animals#eagle01,positive examples,1,HasEggs,Homeothermic,animals#eagle01,0.303576,-0.257578,0.161850,...,-0.310711,-0.322468,-0.197063,0.01235,-0.083662,0.070967,0.030652,-0.291009,-0.04082,0.330059
1,HasEggs ⊓ Homeothermic,animals#ostrich01,positive examples,1,HasEggs,Homeothermic,animals#ostrich01,0.244503,-0.165339,0.238183,...,-0.310711,-0.322468,-0.197063,0.01235,-0.083662,0.070967,0.030652,-0.291009,-0.04082,0.330059
2,HasEggs ⊓ Homeothermic,animals#penguin01,positive examples,1,HasEggs,Homeothermic,animals#penguin01,0.251046,-0.165633,0.311441,...,-0.310711,-0.322468,-0.197063,0.01235,-0.083662,0.070967,0.030652,-0.291009,-0.04082,0.330059
3,HasEggs ⊓ Homeothermic,animals#platypus01,positive examples,1,HasEggs,Homeothermic,animals#platypus01,0.256755,0.015516,0.219961,...,-0.310711,-0.322468,-0.197063,0.01235,-0.083662,0.070967,0.030652,-0.291009,-0.04082,0.330059
4,HasEggs ⊓ Homeothermic,animals#eagle01,positive examples,1,HasEggs,Homeothermic,animals#eagle01,0.303576,-0.257578,0.161850,...,-0.310711,-0.322468,-0.197063,0.01235,-0.083662,0.070967,0.030652,-0.291009,-0.04082,0.330059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7325,HasEggs ⊓ ¬Shark,animals#shark01,negative examples,0,HasEggs,¬Shark,animals#shark01,0.265107,0.035628,0.237405,...,-0.310711,-0.322468,-0.197063,0.01235,-0.083662,0.070967,0.030652,-0.291009,-0.04082,0.330059
7326,HasEggs ⊓ ¬Shark,animals#boy01,negative examples,0,HasEggs,¬Shark,animals#boy01,0.326895,-0.017734,0.072276,...,-0.310711,-0.322468,-0.197063,0.01235,-0.083662,0.070967,0.030652,-0.291009,-0.04082,0.330059
7327,HasEggs ⊓ ¬Shark,animals#bat01,negative examples,0,HasEggs,¬Shark,animals#bat01,0.252662,-0.221016,0.193865,...,-0.310711,-0.322468,-0.197063,0.01235,-0.083662,0.070967,0.030652,-0.291009,-0.04082,0.330059
7328,HasEggs ⊓ ¬Shark,animals#dragon01,negative examples,0,HasEggs,¬Shark,animals#dragon01,0.071034,-0.154344,0.204145,...,-0.310711,-0.322468,-0.197063,0.01235,-0.083662,0.070967,0.030652,-0.291009,-0.04082,0.330059
7329,HasEggs ⊓ ¬Shark,animals#cat01,negative examples,0,HasEggs,¬Shark,animals#cat01,0.183570,0.064570,0.119314,...,-0.310711,-0.322468,-0.197063,0.01235,-0.083662,0.070967,0.030652,-0.291009,-0.04082,0.330059

In [19]:
conj_ent = pd.merge(conj_ent, atomic_neg, left_on="Part2", right_on='Expression', how='left')#, suffixes=['_ind', '_cla2'])
conj_ent

,Expression_x,Individual,Example Type,Example Encoding,Part1,Part2,Unnamed: 0_ind,0_ind,1_ind,2_ind,...,30_cla,31_cla,32_cla,33_cla,34_cla,35_cla,36_cla,37_cla,38_cla,39_cla
0,HasEggs ⊓ Homeothermic,animals#eagle01,positive examples,1,HasEggs,Homeothermic,animals#eagle01,0.303576,-0.257578,0.161850,...,-0.144161,-0.369990,-0.131314,0.014287,-0.342975,-0.559696,-0.073750,-0.346391,-0.080756,0.412077
1,HasEggs ⊓ Homeothermic,animals#ostrich01,positive examples,1,HasEggs,Homeothermic,animals#ostrich01,0.244503,-0.165339,0.238183,...,-0.144161,-0.369990,-0.131314,0.014287,-0.342975,-0.559696,-0.073750,-0.346391,-0.080756,0.412077
2,HasEggs ⊓ Homeothermic,animals#penguin01,positive examples,1,HasEggs,Homeothermic,animals#penguin01,0.251046,-0.165633,0.311441,...,-0.144161,-0.369990,-0.131314,0.014287,-0.342975,-0.559696,-0.073750,-0.346391,-0.080756,0.412077
3,HasEggs ⊓ Homeothermic,animals#platypus01,positive examples,1,HasEggs,Homeothermic,animals#platypus01,0.256755,0.015516,0.219961,...,-0.144161,-0.369990,-0.131314,0.014287,-0.342975,-0.559696,-0.073750,-0.346391,-0.080756,0.412077
4,HasEggs ⊓ Homeothermic,animals#eagle01,positive examples,1,HasEggs,Homeothermic,animals#eagle01,0.303576,-0.257578,0.161850,...,-0.144161,-0.369990,-0.131314,0.014287,-0.342975,-0.559696,-0.073750,-0.346391,-0.080756,0.412077
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7325,HasEggs ⊓ ¬Shark,animals#shark01,negative examples,0,HasEggs,¬Shark,animals#shark01,0.265107,0.035628,0.237405,...,0.276986,0.357759,-0.305159,0.325288,0.289673,0.294649,0.054776,0.247871,0.088878,-0.438255
7326,HasEggs ⊓ ¬Shark,animals#boy01,negative examples,0,HasEggs,¬Shark,animals#boy01,0.326895,-0.017734,0.072276,...,0.276986,0.357759,-0.305159,0.325288,0.289673,0.294649,0.054776,0.247871,0.088878,-0.438255
7327,HasEggs ⊓ ¬Shark,animals#bat01,negative examples,0,HasEggs,¬Shark,animals#bat01,0.252662,-0.221016,0.193865,...,0.276986,0.357759,-0.305159,0.325288,0.289673,0.294649,0.054776,0.247871,0.088878,-0.438255
7328,HasEggs ⊓ ¬Shark,animals#dragon01,negative examples,0,HasEggs,¬Shark,animals#dragon01,0.071034,-0.154344,0.204145,...,0.276986,0.357759,-0.305159,0.325288,0.289673,0.294649,0.054776,0.247871,0.088878,-0.438255
7329,HasEggs ⊓ ¬Shark,animals#cat01,negative examples,0,HasEggs,¬Shark,animals#cat01,0.183570,0.064570,0.119314,...,0.276986,0.357759,-0.305159,0.325288,0.289673,0.294649,0.054776,0.247871,0.088878,-0.438255

In [20]:
# pd.concat([conj_ent, atomic_neg], axis=1)
# conj_ent.join(atomic_neg)
conj_ent.head()

,Expression_x,Individual,Example Type,Example Encoding,Part1,Part2,Unnamed: 0_ind,0_ind,1_ind,2_ind,...,30_cla,31_cla,32_cla,33_cla,34_cla,35_cla,36_cla,37_cla,38_cla,39_cla
0,HasEggs ⊓ Homeothermic,animals#eagle01,positive examples,1,HasEggs,Homeothermic,animals#eagle01,0.303576,-0.257578,0.161850,...,-0.144161,-0.36999,-0.131314,0.014287,-0.342975,-0.559696,-0.07375,-0.346391,-0.080756,0.412077
1,HasEggs ⊓ Homeothermic,animals#ostrich01,positive examples,1,HasEggs,Homeothermic,animals#ostrich01,0.244503,-0.165339,0.238183,...,-0.144161,-0.36999,-0.131314,0.014287,-0.342975,-0.559696,-0.07375,-0.346391,-0.080756,0.412077
2,HasEggs ⊓ Homeothermic,animals#penguin01,positive examples,1,HasEggs,Homeothermic,animals#penguin01,0.251046,-0.165633,0.311441,...,-0.144161,-0.36999,-0.131314,0.014287,-0.342975,-0.559696,-0.07375,-0.346391,-0.080756,0.412077
3,HasEggs ⊓ Homeothermic,animals#platypus01,positive examples,1,HasEggs,Homeothermic,animals#platypus01,0.256755,0.015516,0.219961,...,-0.144161,-0.36999,-0.131314,0.014287,-0.342975,-0.559696,-0.07375,-0.346391,-0.080756,0.412077
4,HasEggs ⊓ Homeothermic,animals#eagle01,positive examples,1,HasEggs,Homeothermic,animals#eagle01,0.303576,-0.257578,0.161850,...,-0.144161,-0.36999,-0.131314,0.014287,-0.342975,-0.559696,-0.07375,-0.346391,-0.080756,0.412077

In [21]:
print(list(conj_ent.columns))

['Expression_x', 'Individual', 'Example Type', 'Example Encoding', 'Part1', 'Part2', 'Unnamed: 0_ind', '0_ind', '1_ind', '2_ind', '3_ind', '4_ind', '5_ind', '6_ind', '7_ind', '8_ind', '9_ind', '10_ind', '11_ind', '12_ind', '13_ind', '14_ind', '15_ind', '16_ind', '17_ind', '18_ind', '19_ind', '20_ind', '21_ind', '22_ind', '23_ind', '24_ind', '25_ind', '26_ind', '27_ind', '28_ind', '29_ind', '30_ind', '31_ind', '32_ind', '33_ind', '34_ind', '35_ind', '36_ind', '37_ind', '38_ind', '39_ind', 'Unnamed: 0_cla1', '0_cla1', '1_cla1', '2_cla1', '3_cla1', '4_cla1', '5_cla1', '6_cla1', '7_cla1', '8_cla1', '9_cla1', '10_cla1', '11_cla1', '12_cla1', '13_cla1', '14_cla1', '15_cla1', '16_cla1', '17_cla1', '18_cla1', '19_cla1', '20_cla1', '21_cla1', '22_cla1', '23_cla1', '24_cla1', '25_cla1', '26_cla1', '27_cla1', '28_cla1', '29_cla1', '30_cla1', '31_cla1', '32_cla1', '33_cla1', '34_cla1', '35_cla1', '36_cla1', '37_cla1', '38_cla1', '39_cla1', 'Expression_y', '0_cla', '1_cla', '2_cla', '3_cla', '4_cla', '5_cla', '6_cla', '7_cla', '8_cla', '9_cla', '10_cla', '11_cla', '12_cla', '13_cla', '14_cla', '15_cla', '16_cla', '17_cla', '18_cla', '19_cla', '20_cla', '21_cla', '22_cla', '23_cla', '24_cla', '25_cla', '26_cla', '27_cla', '28_cla', '29_cla', '30_cla', '31_cla', '32_cla', '33_cla', '34_cla', '35_cla', '36_cla', '37_cla', '38_cla', '39_cla']

In [26]:
X = conj_ent[['0_ind', '1_ind', '2_ind', '3_ind', '4_ind', '5_ind', '6_ind', '7_ind', '8_ind', '9_ind', '10_ind', '11_ind', '12_ind', '13_ind', '14_ind', '15_ind', '16_ind', '17_ind', '18_ind', '19_ind', '20_ind', '21_ind', '22_ind', '23_ind', '24_ind', '25_ind', '26_ind', '27_ind', '28_ind', '29_ind', '30_ind', '31_ind', '32_ind', '33_ind', '34_ind', '35_ind', '36_ind', '37_ind', '38_ind', '39_ind',\
             '0_cla', '1_cla', '2_cla', '3_cla', '4_cla', '5_cla', '6_cla', '7_cla', '8_cla', '9_cla', '10_cla', '11_cla', '12_cla', '13_cla', '14_cla', '15_cla', '16_cla', '17_cla', '18_cla', '19_cla', '20_cla', '21_cla', '22_cla', '23_cla', '24_cla', '25_cla', '26_cla', '27_cla', '28_cla', '29_cla', '30_cla', '31_cla', '32_cla', '33_cla', '34_cla', '35_cla', '36_cla', '37_cla', '38_cla', '39_cla',\
             '0_cla1', '1_cla1', '2_cla1', '3_cla1', '4_cla1', '5_cla1', '6_cla1', '7_cla1', '8_cla1', '9_cla1', '10_cla1', '11_cla1', '12_cla1', '13_cla1', '14_cla1', '15_cla1', '16_cla1', '17_cla1', '18_cla1', '19_cla1', '20_cla1', '21_cla1', '22_cla1', '23_cla1', '24_cla1', '25_cla1', '26_cla1', '27_cla1', '28_cla1', '29_cla1', '30_cla1', '31_cla1', '32_cla1', '33_cla1', '34_cla1', '35_cla1', '36_cla1', '37_cla1', '38_cla1', '39_cla1'
            ]]
y = conj_ent['Example Encoding']

In [27]:
# Hyperparameters
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

# Convert data to PyTorch tensors
X_train_tensor = torch.tensor(X_train.values, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test.values, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.long)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.long)

X_train_tensor = torch.reshape(X_train_tensor, (X_train_tensor.shape[0], 1, X_train_tensor.shape[1]))
X_test_tensor = torch.reshape(X_test_tensor, (X_test_tensor.shape[0], 1, X_test_tensor.shape[1]))
y_train_tensor = torch.reshape(y_train_tensor, (y_train_tensor.shape[0], 1, y_train_tensor.shape[1]))
y_test_tensor = torch.reshape(y_test_tensor, (y_test_tensor.shape[0], 1, y_test_tensor.shape[1]))


# Define hyperparameters
input_size = X_train.shape[1]
hidden_size = 60
output_size = 2 # num_classes = 2
num_layers = 2
learning_rate = 0.1
num_epochs = 1000
batch_size = 50

IndexError: tuple index out of range

In [25]:
# X_train_tensor.shape
print("Training Shape", X_train_tensor.shape, y_train_tensor.shape)
print("Testing Shape", X_test_tensor.shape, y_test_tensor.shape)

Training Shape torch.Size([5864, 1, 120]) torch.Size([5864])
Testing Shape torch.Size([1466, 1, 120]) torch.Size([1466])